### ISSUE TITLE
spring-boot-web-api-data project couldn't start

### ISSUE THREAD

**Issue by bobzh39** [macauyeah/spring-boot-demo#1]
version:
java version "17.0.6" 2023-01-17 LTS
Java(TM) SE Runtime Environment (build 17.0.6+9-LTS-190)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.6+9-LTS-190, mixed mode, sharing)

2024-10-08T16:45:28.465+08:00 ERROR 10384 --- [springbootwebapidata] [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

A component required a bean of type 'io.github.macauyeah.springboot.tutorial.springbootwebapidata.repo.UserRepo' that could not be found.

Action:

Consider defining a bean of type 'io.github.macauyeah.springboot.tutorial.springbootwebapidata.repo.UserRepo' in your configuration.

**Comment by macauyeah** [comment]
@bobzh39 how do you run the program ? Did you try the maven build command?

```bash
cd spring-boot-tutorial/spring-boot-web-api-data/
mvn clean compile spring-boot:run
```

**Comment by macauyeah** [comment]
@bobzh39  I directly opened this project by github codespace, spring-boot-web-api-data could run without any error

![image](https://github.com/user-attachments/assets/c3b5ebcd-91f9-4d34-87d8-2aea6657e9c0)

and also, try the standard maven spring-boot command 

```bash
cd spring-boot-tutorial/spring-boot-web-api-data/
mvn clean compile spring-boot:run
```

it works fine.

**Comment by macauyeah** [comment]
@bobzh39  if you run by Intellij Idea community edition, you may need to delete the scope of  `spring-boot-starter-tomcat`

[spring-boot-tutorial/spring-boot-web-api-data/pom.xml](https://github.com/macauyeah/spring-boot-demo/blob/main/spring-boot-tutorial/spring-boot-web-api-data/pom.xml)

```diff
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-tomcat</artifactId>
-			<scope>provided</scope>
		</dependency>
```
